#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#
#################MY PART#####################
def diagonalDifference(arr):
    # Write your code here
    LRdiag = 0
    RLdiag = 0
    diff = 0
    n = len(arr)
    for i in range(n):
        LRdiag = LRdiag + arr[i][i]
        RLdiag = RLdiag + arr[i][n-1-i]
    diff = LRdiag - RLdiag
    return abs(diff)
#############END OF MY PART####################
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
