#!/bin/python3

import math
import os
import random
import re
import sys
# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    minimum = 0
    maximum = 0
    n = len(arr)
    for i in range(n):
        minimum += arr[i]
    for i in range(n):
        maximum += arr[i]
    minimum = minimum - max(arr)
    maximum = maximum - min(arr)
    print(minimum, maximum)
if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
