#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    positive = 0
    negative = 0
    zero = 0
    for i in range(len(arr)):
        if arr[i] > 0:
            positive += 1
        if arr[i] < 0:
            negative +=1
        if arr[i] == 0:
            zero +=1
    positive = round(positive/len(arr),6)
    negative = round(negative/len(arr),6)
    zero = round(zero/len(arr),6)
    print('%.6f'%positive)
    print('%.6f'%negative)
    print('%.6f'%zero) 
if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
